config/routes.rb
Rails.application.routes.draw do
  resources :kernelperears
  resources :sitefactors
  resources :projlines do
      collection { post :import}
  end
  post 'runscript'   => 'static_pages#runscript'
  root "static_pages#landing"
  get 'results'   => 'static_pages#results'
  get 'download_template', to: "static_pages#download_template"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/sitefactor.rb
class Sitefactor < ApplicationRecord
end

app/controllers/sitefactors_controller.rb
class SitefactorsController < ApplicationController
  before_action :set_sitefactor, only: [:show, :edit, :update, :destroy]

  # GET /sitefactors
  # GET /sitefactors.json
  def index
    @sitefactors = Sitefactor.all
  end

  # GET /sitefactors/1
  # GET /sitefactors/1.json
  def show
  end

  # GET /sitefactors/new
  def new
    @sitefactor = Sitefactor.new
  end

  # GET /sitefactors/1/edit
  def edit
  end

  # POST /sitefactors
  # POST /sitefactors.json
  def create
    @sitefactor = Sitefactor.new(sitefactor_params)

    respond_to do |format|
      if @sitefactor.save
        format.html { redirect_to @sitefactor, notice: 'Sitefactor was successfully created.' }
        format.json { render :show, status: :created, location: @sitefactor }
      else
        format.html { render :new }
        format.json { render json: @sitefactor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sitefactors/1
  # PATCH/PUT /sitefactors/1.json
  def update
    respond_to do |format|
      if @sitefactor.update(sitefactor_params)
        format.html { redirect_to @sitefactor, notice: 'Sitefactor was successfully updated.' }
        format.json { render :show, status: :ok, location: @sitefactor }
      else
        format.html { render :edit }
        format.json { render json: @sitefactor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sitefactors/1
  # DELETE /sitefactors/1.json
  def destroy
    @sitefactor.destroy
    respond_to do |format|
      format.html { redirect_to sitefactors_url, notice: 'Sitefactor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sitefactor
      @sitefactor = Sitefactor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sitefactor_params
      params.fetch(:sitefactor, {})
    end
end

app/helpers/sitefactors_helper.rb
module SitefactorsHelper
end

app/views/sitefactors/_form.html.erb
<%= form_with(model: sitefactor, local: true) do |form| %>
  <% if sitefactor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sitefactor.errors.count, "error") %> prohibited this sitefactor from being saved:</h2>

      <ul>
      <% sitefactor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sitefactors/edit.html.erb
<h1>Editing Sitefactor</h1>

<%= render 'form', sitefactor: @sitefactor %>

<%= link_to 'Show', @sitefactor %> |
<%= link_to 'Back', sitefactors_path %>

app/views/sitefactors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sitefactors</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sitefactors.each do |sitefactor| %>
      <tr>
        <td><%= link_to 'Show', sitefactor %></td>
        <td><%= link_to 'Edit', edit_sitefactor_path(sitefactor) %></td>
        <td><%= link_to 'Destroy', sitefactor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sitefactor', new_sitefactor_path %>

app/views/sitefactors/new.html.erb
<h1>New Sitefactor</h1>

<%= render 'form', sitefactor: @sitefactor %>

<%= link_to 'Back', sitefactors_path %>

app/views/sitefactors/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_sitefactor_path(@sitefactor) %> |
<%= link_to 'Back', sitefactors_path %>