config/routes.rb
Rails.application.routes.draw do
  resources :kernelperears
  resources :sitefactors
  resources :projlines do
      collection { post :import}
  end
  post 'runscript'   => 'static_pages#runscript'
  root "static_pages#landing"
  get 'results'   => 'static_pages#results'
  get 'download_template', to: "static_pages#download_template"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def landing
		@projlines = Projline.where(b1pop: nil)
		@projlines1 = Projline.where.not(f2pop: nil).order('id ASC')
	end
	def runscript
		@projlines = Projline.where(b1pop: nil).each do |proj|
			initrecovery = (1.000-proj.neisValue)*0.500+proj.neisValue
			if proj.targetSelfingGen.eql?("B4")
				bc4target = proj.targetRprecoveryThreshold
			elsif proj.targetSelfingGen.eql?("B3")
				bc3target = proj.targetRprecoveryThreshold
			elsif proj.targetSelfingGen.eql?("B2")
				bc2target = proj.targetRprecoveryThreshold
			elsif proj.targetSelfingGen.eql?("B1")
				bc1target = proj.targetRprecoveryThreshold
			end
			
			if proj.targetSelfingGen.eql?("B1")
				bc2target = proj.targetRprecoveryThreshold
				bc3target = proj.targetRprecoveryThreshold
				bc4target = proj.targetRprecoveryThreshold
			elsif proj.targetSelfingGen.eql?("B2")
				bc1target = (eval("bc" + proj.targetSelfingGen.split(//).last + "target") - initrecovery) * 0.4 + initrecovery
				bc3target = proj.targetRprecoveryThreshold
				bc4target = proj.targetRprecoveryThreshold
			elsif proj.targetSelfingGen.eql?("B3")
				bc1target = (proj.targetRprecoveryThreshold - initrecovery) * 0.40 + initrecovery
				bc2target = (proj.targetRprecoveryThreshold - initrecovery) * 0.30 + bc1target
				bc4target = proj.targetRprecoveryThreshold
			elsif proj.targetSelfingGen.eql?("B4")
				bc1target = (proj.targetRprecoveryThreshold - initrecovery) * 0.40 + initrecovery
				bc2target = (proj.targetRprecoveryThreshold - initrecovery) * 0.30 + bc1target
				bc3target = (proj.targetRprecoveryThreshold - initrecovery) * 0.20 + bc2target
			end
			bc4target = proj.targetRprecoveryThreshold
			selgen = proj.targetSelfingGen.split(//).last.to_i
			traitcount = proj.traits.count(";")+1
			certainty = proj.certainty
			frequency = 0.5**traitcount
			neisValue = proj.neisValue
			f3frequency = 0.5**(traitcount*2)
			f3desired = proj.targetF3Material
			f3adjustment = Sitefactor.find_by(site:proj.f2Site).factor
			bc4sitefactor = Sitefactor.find_by(site:proj.bc4Site).factor
			bc3sitefactor = Sitefactor.find_by(site:proj.bc3Site).factor
			bc2sitefactor = Sitefactor.find_by(site:proj.bc2Site).factor
			bc1sitefactor = Sitefactor.find_by(site:proj.bc1Site).factor
			f1sitefactor = Sitefactor.find_by(site:proj.f1Site).factor
			nssitefactor = Sitefactor.find_by(site:proj.nsSite).factor
			bc4sitekpe = Kernelperear.find_by(site:proj.bc4Site).avgkernelperear
			bc3sitekpe = Kernelperear.find_by(site:proj.bc3Site).avgkernelperear
			bc2sitekpe = Kernelperear.find_by(site:proj.bc2Site).avgkernelperear
			bc1sitekpe = Kernelperear.find_by(site:proj.bc1Site).avgkernelperear
			f1sitekpe = Kernelperear.find_by(site:proj.f1Site).avgkernelperear
			nssitekpe = Kernelperear.find_by(site:proj.nsSite).avgkernelperear
			filepath = Rails.root.join("lib", "rscripts", "rscript.R")
			output = `Rscript --vanilla #{filepath} #{selgen} #{certainty} #{traitcount} #{f3desired} #{f3adjustment} #{bc4target} #{bc3target} #{bc2target} #{bc1target} #{initrecovery} #{bc4sitefactor} #{bc4sitekpe} #{bc3sitefactor} #{bc3sitekpe} #{bc2sitefactor} #{bc2sitekpe} #{bc1sitefactor} #{bc1sitekpe} #{f1sitefactor} #{f1sitekpe} #{nssitefactor} #{nssitekpe}`
			array = []
			puts output
			a = output.gsub(/\s+/, "").split(/"/)
			a.each do |y|
				array << y
			end
			proj.update(f2pop: array[1], b4pop: array[3], b3pop: array[5], b2pop: array[7], b1pop: array[9], f1pop: array[11], nspop: array[13])
			puts(initrecovery)
			puts(bc1target)
			puts(bc2target)
			puts(bc3target)
			puts(bc4target)
		end
		redirect_to results_path, notice: "Calculator ran successfully, see results below"
	end	
	def results
		@projlines1 = Projline.where.not(f2pop: nil).order('id ASC')
	end
	def download_template
		send_file "#{Rails.root}/lib/assets/popcalc_template.csv", type: "application/csv", x_sendfile: true

	end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/landing.html.erb
<center>
<div class='booyah-box col-10'>

  <table id="bingo1" class="display nowrap" title="Project List">
    <thead>
      <tr>
        <th>ID</th>
        <th>PIDTC</th>
        <th>Job Name</th>
        <th>Crop</th>
        <th>Traits</th>
        <th>NEIS Value</th>
        <th>Selfing RP Threshold</th>
        <th>Selfing Generation</th>
        <th>Confidence Level</th>
        <th>F3 IE's at Handoff</th>
        <th>NS Site</th>
        <th>F1 Site</th>
        <th>B1 Site</th>
        <th>B2 Site</th>
        <th>B3 Site</th>
        <th>B4 Site</th>
        <th>F2 Site</th>
      </tr>
    </thead>
    <tbody>
      <% @projlines.each do |p| %>
        <tr>
          <td><%= p.id %></td>
          <td><%= p.pidtc %></td>
          <td><%= p.jobName %></td>
          <td><%= p.crop %></td>
          <td><%= p.traits %></td>
          <td><%= p.neisValue %></td>
          <td><%= p.targetRprecoveryThreshold %></td>
          <td><%= p.targetSelfingGen %></td>
          <td><%= p.certainty %></td>
          <td><%= p.targetF3Material %></td>
          <td><%= p.nsSite %></td>
          <td><%= p.f1Site %></td>
          <td><%= p.bc1Site %></td>
          <td><%= p.bc2Site %></td>
          <td><%= p.bc3Site %></td>
          <td><%= p.bc4Site %></td>
          <td><%= p.f2Site %></td>

        </tr>
      <% end %>
    </tbody>
  </table>
  <span class="pull-left">
    Showing 
    <span id="myLink">
    </span> of 
    <span id="totalRows"> Total
    </span>
  </span>
  <br />
  <br />
  <%= button_to "Run Calculator", runscript_path, class: 'btn btn-primary' %>
</div>

<br />
<br />




</center>
<script>
$(function(){
  setInterval(oneSecondFunction, 10);
});

function oneSecondFunction() {
// stuff to do every second
  var numOfVisibleRows = $('tr:has(td:visible)').length;
  document.getElementById("myLink").innerHTML=numOfVisibleRows;
};

$( document ).on('turbolinks:load', function() {
  jQuery(".best_in_place").best_in_place();
  var totalRows = $('tr').length - $('thead>tr').length;
  document.getElementById("totalRows").innerHTML=totalRows;
  $('#bingo1').excelTableFilter();
  $('#bingo1').DataTable( {
    colReorder: true,
    "bSort" : false,
    "paging": false,
    scrollY: '65vh',
    info: false,
    scrollCollapse: true,
    "dom": '<"toolbar">frtp',
    searching: false,
    select: true,
    scrollX: true,
    bJQueryUI: true,
    pagingType: "simple",
    bDestroy: true,
  });
    $("div.toolbar").html("<div class='pull-left'><h3 style='font-family: sans-serif;'>Staging Data</h3></div><div class='pull-right'><div class='dropdown'><button onclick='myFunction()' class='dropbtn btn btn-primary'><i style='color:#45c4af; font-size:15px;' class='fa fa-caret-down'></i> Options</button><div id='myDropdown' class='dropdown-content'><a href='#bingoModal' data-toggle='modal' data-target='#bingoModal' style='color:white'><i style='color:#45c4af; font-size:15px;' class='fa fa-upload'></i> Import New </a>");
    
function exportTableToCSV($table, filename) {
                var $headers = $table.find('tr:has(th)')
                    ,$rows = $table.find('tr:has(td:visible)')
                    // Temporary delimiter characters unlikely to be typed by keyboard
                    // This is to avoid accidentally splitting the actual contents
                    ,tmpColDelim = String.fromCharCode(11) // vertical tab character
                    ,tmpRowDelim = String.fromCharCode(0) // null character
                    // actual delimiter characters for CSV format
                    ,colDelim = '","'
                    ,rowDelim = '"\r\n"';
                    // Grab text from table into CSV formatted string
                    var csv = '"';
                    csv += formatRows($headers.map(grabRow));
                    csv += rowDelim;
                    csv += formatRows($rows.map(grabRow)) + '"';
                    // Data URI
                    var csvData = 'data:application/csv;charset=utf-8,' + encodeURIComponent(csv);
                $(this)
                    .attr({
                    'download': filename
                        ,'href': csvData
                        //,'target' : '_blank' //if you want it to open in a new window
                });
                //------------------------------------------------------------
                // Helper Functions 
                //------------------------------------------------------------
                // Format the output so it has the appropriate delimiters
                function formatRows(rows){
                    return rows.get().join(tmpRowDelim)
                        .split(tmpRowDelim).join(rowDelim)
                        .split(tmpColDelim).join(colDelim);
                };
                // Grab and format a row from the table
                function grabRow(i,row){
                     
                    var $row = $(row);
                    //for some reason $cols = $row.find('td') || $row.find('th') won't work...
                    var $cols = $row.find('td'); 
                    if(!$cols.length) $cols = $row.find('th .dataTables_sizing').clone().children().remove().end();  
                    return $cols.map(grabCol)
                                .get().join(tmpColDelim);
                };
                // Grab and format a column from the table 
                function grabCol(j,col){
                    var $col = $(col),
                        $text = $col.text();
                    return $text.replace('"', '""'); // escape double quotes
                };
            }
            // This must be a hyperlink
            $("#export").click(function (event) {
                // var outputFile = 'export'
                var outputFile = window.prompt("What do you want to name your output file?") || 'export';
                outputFile = outputFile.replace('.csv','') + '.csv'
                 
                // CSV
                exportTableToCSV.apply(this, [$('#bingo1'), outputFile]);
                
                // IF CSV, don't do event.preventDefault() or return false
                // We actually need this to be a typical hyperlink
            }); 



});
function myFunction() {
    document.getElementById("myDropdown").classList.toggle("show");
}

// Close the dropdown menu if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {

    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
};
</script>
<!-- Modal -->
<div class="modal fade" id="bingoModal" tabindex="-1" role="dialog" aria-labelledby="bingoModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="bingoModalLabel">Import Project Data</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= link_to "Download Upload Template", download_template_path %>
        <br />
        <%= form_tag import_projlines_path, multipart: true do %>
          <%= file_field_tag :file %><br />
          <%= submit_tag "Upload!" %>
        <% end %>
      </div>      
    </div>
  </div>
</div>

app/views/static_pages/results.html.erb
<center>
<div class='booyah-box col-10'>
  <table id="bingo" class="display nowrap" title="Results">
    <thead>
      <tr>
        <th>ID</th>
        <th>PIDTC</th>
        <th>Job Name</th>
        <th>Crop</th>
        <th>Traits</th>
        <th>NEIS Value</th>
        <th>Selfing RP Threshold</th>
        <th>Selfing Generation</th>
        <th>Confidence Level</th>
        <th>F3 IE's at Handoff</th>
        <th>NS Site</th>
        <th>F1 Site</th>
        <th>B1 Site</th>
        <th>B2 Site</th>
        <th>B3 Site</th>
        <th>B4 Site</th>
        <th>F2 Site</th>
        <th>NS Population</th>
        <th>F1 Population</th>
        <th>B1 Population</th>
        <th>B2 Population</th>
        <th>B3 Population</th>
        <th>B4 Population</th>
        <th>F2 Population</th>
      </tr>
    </thead>
    <tbody>
      <% @projlines1.each do |p| %>
        <tr>
                    <td><%= p.id %></td>

          <td><%= p.pidtc %></td>
          <td><%= p.jobName %></td>
          <td><%= p.crop %></td>
          <td><%= p.traits %></td>
          <td><%= p.neisValue %></td>
          <td><%= p.targetRprecoveryThreshold %></td>
          <td><%= p.targetSelfingGen %></td>
          <td><%= p.certainty %></td>
          <td><%= p.targetF3Material %></td>
          <td><%= p.nsSite %></td>
          <td><%= p.f1Site %></td>
          <td><%= p.bc1Site %></td>
          <td><%= p.bc2Site %></td>
          <td><%= p.bc3Site %></td>
          <td><%= p.bc4Site %></td>
          <td><%= p.f2Site %></td>
          <td><%= p.nspop %></td>
          <td><%= p.f1pop %></td>
          <td><%= p.b1pop %></td>
          <td><%= p.b2pop %></td>
          <td><%= p.b3pop %></td>
          <td><%= p.b4pop %></td>
          <td><%= p.f2pop %></td>

        </tr>
      <% end %>
    </tbody>
  </table>
  <span class="pull-left">
    Showing 
    <span id="myLink">
    </span> of 
    <span id="totalRows"> Total
    </span>
  </span>
  </div>
</center>
<script>
$(function(){
  setInterval(oneSecondFunction, 10);
});

function oneSecondFunction() {
// stuff to do every second
  var numOfVisibleRows = $('tr:has(td:visible)').length;
  document.getElementById("myLink").innerHTML=numOfVisibleRows;
};

$( document ).on('turbolinks:load', function() {
  jQuery(".best_in_place").best_in_place();
  var totalRows = $('tr').length - $('thead>tr').length;
  document.getElementById("totalRows").innerHTML=totalRows;
  $('#bingo').excelTableFilter();
  $('#bingo').DataTable( {
    colReorder: true,
    "bSort" : false,
    "paging": false,
    scrollY: '65vh',
    info: false,
    scrollCollapse: true,
    "dom": '<"toolbar">frtp',
    searching: false,
    select: true,
    scrollX: true,
    bJQueryUI: true,
    pagingType: "simple",
    bDestroy: true,
  });
    $("div.toolbar").html("<div class='pull-left'><h3>Results</h3></div><div class='pull-right'><div class='dropdown'><button onclick='myFunction()' class='dropbtn btn btn-primary'><i style='color:#45c4af; font-size:15px;' class='fa fa-caret-down'></i> Options</button><div id='myDropdown' class='dropdown-content'><a href='#' id='export' role='button' style='color: white;'><i style='color:#45c4af; font-size:15px;' class='fa fa-file'></i>Export Results</a></div></div></div><br /><br />");
    
function exportTableToCSV($table, filename) {
                var $headers = $table.find('tr:has(th)')
                    ,$rows = $table.find('tr:has(td:visible)')
                    // Temporary delimiter characters unlikely to be typed by keyboard
                    // This is to avoid accidentally splitting the actual contents
                    ,tmpColDelim = String.fromCharCode(11) // vertical tab character
                    ,tmpRowDelim = String.fromCharCode(0) // null character
                    // actual delimiter characters for CSV format
                    ,colDelim = '","'
                    ,rowDelim = '"\r\n"';
                    // Grab text from table into CSV formatted string
                    var csv = '"';
                    csv += formatRows($headers.map(grabRow));
                    csv += rowDelim;
                    csv += formatRows($rows.map(grabRow)) + '"';
                    // Data URI
                    var csvData = 'data:application/csv;charset=utf-8,' + encodeURIComponent(csv);
                $(this)
                    .attr({
                    'download': filename
                        ,'href': csvData
                        //,'target' : '_blank' //if you want it to open in a new window
                });
                //------------------------------------------------------------
                // Helper Functions 
                //------------------------------------------------------------
                // Format the output so it has the appropriate delimiters
                function formatRows(rows){
                    return rows.get().join(tmpRowDelim)
                        .split(tmpRowDelim).join(rowDelim)
                        .split(tmpColDelim).join(colDelim);
                };
                // Grab and format a row from the table
                function grabRow(i,row){
                     
                    var $row = $(row);
                    //for some reason $cols = $row.find('td') || $row.find('th') won't work...
                    var $cols = $row.find('td'); 
                    if(!$cols.length) $cols = $row.find('th .dataTables_sizing').clone().children().remove().end();  
                    return $cols.map(grabCol)
                                .get().join(tmpColDelim);
                };
                // Grab and format a column from the table 
                function grabCol(j,col){
                    var $col = $(col),
                        $text = $col.text();
                    return $text.replace('"', '""'); // escape double quotes
                };
            }
            // This must be a hyperlink
            $("#export").click(function (event) {
                // var outputFile = 'export'
                var outputFile = window.prompt("What do you want to name your output file?") || 'export';
                outputFile = outputFile.replace('.csv','') + '.csv'
                 
                // CSV
                exportTableToCSV.apply(this, [$('#bingo'), outputFile]);
                
                // IF CSV, don't do event.preventDefault() or return false
                // We actually need this to be a typical hyperlink
            }); 



});
function myFunction() {
    document.getElementById("myDropdown").classList.toggle("show");
}

// Close the dropdown menu if the user clicks outside of it
window.onclick = function(event) {
  if (!event.target.matches('.dropbtn')) {

    var dropdowns = document.getElementsByClassName("dropdown-content");
    var i;
    for (i = 0; i < dropdowns.length; i++) {
      var openDropdown = dropdowns[i];
      if (openDropdown.classList.contains('show')) {
        openDropdown.classList.remove('show');
      }
    }
  }
};
</script>