config/routes.rb
Rails.application.routes.draw do
  resources :kernelperears
  resources :sitefactors
  resources :projlines do
      collection { post :import}
  end
  post 'runscript'   => 'static_pages#runscript'
  root "static_pages#landing"
  get 'results'   => 'static_pages#results'
  get 'download_template', to: "static_pages#download_template"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/kernelperear.rb
class Kernelperear < ApplicationRecord
end

app/controllers/kernelperears_controller.rb
class KernelperearsController < ApplicationController
  before_action :set_kernelperear, only: [:show, :edit, :update, :destroy]

  # GET /kernelperears
  # GET /kernelperears.json
  def index
    @kernelperears = Kernelperear.all
  end

  # GET /kernelperears/1
  # GET /kernelperears/1.json
  def show
  end

  # GET /kernelperears/new
  def new
    @kernelperear = Kernelperear.new
  end

  # GET /kernelperears/1/edit
  def edit
  end

  # POST /kernelperears
  # POST /kernelperears.json
  def create
    @kernelperear = Kernelperear.new(kernelperear_params)

    respond_to do |format|
      if @kernelperear.save
        format.html { redirect_to @kernelperear, notice: 'Kernelperear was successfully created.' }
        format.json { render :show, status: :created, location: @kernelperear }
      else
        format.html { render :new }
        format.json { render json: @kernelperear.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kernelperears/1
  # PATCH/PUT /kernelperears/1.json
  def update
    respond_to do |format|
      if @kernelperear.update(kernelperear_params)
        format.html { redirect_to @kernelperear, notice: 'Kernelperear was successfully updated.' }
        format.json { render :show, status: :ok, location: @kernelperear }
      else
        format.html { render :edit }
        format.json { render json: @kernelperear.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kernelperears/1
  # DELETE /kernelperears/1.json
  def destroy
    @kernelperear.destroy
    respond_to do |format|
      format.html { redirect_to kernelperears_url, notice: 'Kernelperear was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kernelperear
      @kernelperear = Kernelperear.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kernelperear_params
      params.fetch(:kernelperear, {})
    end
end

app/helpers/kernelperears_helper.rb
module KernelperearsHelper
end

app/views/kernelperears/_form.html.erb
<%= form_with(model: kernelperear, local: true) do |form| %>
  <% if kernelperear.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(kernelperear.errors.count, "error") %> prohibited this kernelperear from being saved:</h2>

      <ul>
      <% kernelperear.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/kernelperears/edit.html.erb
<h1>Editing Kernelperear</h1>

<%= render 'form', kernelperear: @kernelperear %>

<%= link_to 'Show', @kernelperear %> |
<%= link_to 'Back', kernelperears_path %>

app/views/kernelperears/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Kernelperears</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kernelperears.each do |kernelperear| %>
      <tr>
        <td><%= link_to 'Show', kernelperear %></td>
        <td><%= link_to 'Edit', edit_kernelperear_path(kernelperear) %></td>
        <td><%= link_to 'Destroy', kernelperear, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Kernelperear', new_kernelperear_path %>

app/views/kernelperears/new.html.erb
<h1>New Kernelperear</h1>

<%= render 'form', kernelperear: @kernelperear %>

<%= link_to 'Back', kernelperears_path %>

app/views/kernelperears/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_kernelperear_path(@kernelperear) %> |
<%= link_to 'Back', kernelperears_path %>