config/routes.rb
Rails.application.routes.draw do
  resources :kernelperears
  resources :sitefactors
  resources :projlines do
      collection { post :import}
  end
  post 'runscript'   => 'static_pages#runscript'
  root "static_pages#landing"
  get 'results'   => 'static_pages#results'
  get 'download_template', to: "static_pages#download_template"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/projline.rb
class Projline < ApplicationRecord

	def self.import(file)
	    headrow = CSV.read(file.path).index(CSV.foreach(file.path).find{|line| line.include?('PIDTC')})
	    heads = CSV.foreach(file.path).find{|line| line.include?('PIDTC')}
	    CSV.foreach(file.path, headers: heads).with_index(0) do |row, rowno|
	    	next if rowno < headrow+1
	    	next if row['PIDTC'].nil? == true
		   	Projline.create({
		    :pidtc => row['PIDTC'],
		    :jobName => row['Job Name (Group of Projects)'],
		    :crop => row['Crop'],
		    :traits => row['Traits From Donor'],
		    :neisValue => row['Neis Value'],
		    :targetRprecoveryThreshold => row['RP Recovery to Self (0.XX format)'],
		    :targetSelfingGen => row['Target Selfing Backcross Generation'],
		    :certainty => row['Certainty Level'],
		    :targetF3Material => row['F3 IEs for Handoff'],
		    :nsSite	=> row['New start location'],
		    :f1Site => row['F1 location'],
		    :bc1Site => row['B1 location'],
		    :bc2Site => row['B2 location'],
		    :bc3Site => row['B3 location'],
		    :bc4Site => row['B4 location'],
		    :f2Site => row['F2 location'],
	      })
	    end
  	end
end

app/controllers/projlines_controller.rb
class ProjlinesController < ApplicationController
  # before_action :set_projline, only: [:show, :edit, :update, :destroy]
    def download_csv
    send_file "#{Rails.root}/public/docs/ti_projects_template.csv", type: "application/csv", x_sendfile: true
  end
  def import
    Projline.import(params[:file])
    redirect_to root_path, notice: "Projects uploaded successfully"
  end
  # GET /projlines
  # GET /projlines.json
  def index
    @projlines = Projline.all
  end

  # GET /projlines/1
  # GET /projlines/1.json
  def show
  end

  # GET /projlines/new
  def new
    @projline = Projline.new
  end

  # GET /projlines/1/edit
  def edit
  end

  # POST /projlines
  # POST /projlines.json
  def create
    @projline = Projline.new(projline_params)

    respond_to do |format|
      if @projline.save
        format.html { redirect_to @projline, notice: 'Projline was successfully created.' }
        format.json { render :show, status: :created, location: @projline }
      else
        format.html { render :new }
        format.json { render json: @projline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projlines/1
  # PATCH/PUT /projlines/1.json
  def update
    respond_to do |format|
      if @projline.update(projline_params)
        format.html { redirect_to @projline, notice: 'Projline was successfully updated.' }
        format.json { render :show, status: :ok, location: @projline }
      else
        format.html { render :edit }
        format.json { render json: @projline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projlines/1
  # DELETE /projlines/1.json
  def destroy
    @projline.destroy
    respond_to do |format|
      format.html { redirect_to projlines_url, notice: 'Projline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_projline
      @projline = Projline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def projline_params
      params.fetch(:projline, {})
    end
end

app/helpers/projlines_helper.rb
module ProjlinesHelper
end

app/views/projlines/_form.html.erb
<%= form_with(model: projline, local: true) do |form| %>
  <% if projline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(projline.errors.count, "error") %> prohibited this projline from being saved:</h2>

      <ul>
      <% projline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projlines/edit.html.erb
<h1>Editing Projline</h1>

<%= render 'form', projline: @projline %>

<%= link_to 'Show', @projline %> |
<%= link_to 'Back', projlines_path %>

app/views/projlines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Projlines</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projlines.each do |projline| %>
      <tr>
        <td><%= link_to 'Show', projline %></td>
        <td><%= link_to 'Edit', edit_projline_path(projline) %></td>
        <td><%= link_to 'Destroy', projline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Projline', new_projline_path %>

app/views/projlines/new.html.erb
<h1>New Projline</h1>

<%= render 'form', projline: @projline %>

<%= link_to 'Back', projlines_path %>

app/views/projlines/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_projline_path(@projline) %> |
<%= link_to 'Back', projlines_path %>